// このファイルはUsefulToolkit.Inputによって自動生成されています。直接編集しないでください。

using UnityEngine;
using UnityEngine.InputSystem.Layouts;
using UnityEngine.InputSystem.LowLevel;
using UnityEngine.InputSystem.Utilities;

namespace AutoGenerated
{
    /// <summary>UsefulInputDevice が持つ状態。スロット1つにつきフィールド1つ。</summary>
    public struct UsefulInputState : IInputStateTypeInfo
    {
        public FourCC format => new FourCC('U', 'T', 'I', 'N');

        [InputControl(name = "TouchLook", layout = "Vector2")]
        public Vector2 TouchLook;

        [InputControl(name = "VrMove", layout = "Vector2")]
        public Vector2 VrMove;

        [InputControl(name = "VrLook", layout = "Vector2")]
        public Vector2 VrLook;
    }
}
