// このファイルはUsefulToolkit.Inputによって自動生成されています。直接編集しないでください。

using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Controls;
using UnityEngine.InputSystem.Layouts;

namespace AutoGenerated
{
    /// <summary>
    /// 外部入力を受ける仮想デバイス。
    /// InputActionAsset からは &lt;UsefulInput&gt;/スロット名 でバインドする。
    /// </summary>
    [InputControlLayout(stateType = typeof(UsefulInputState), displayName = "Useful Input")]
    public sealed class UsefulInputDevice : InputDevice
    {
        public Vector2Control TouchLook { get; private set; }
        public Vector2Control VrMove { get; private set; }
        public Vector2Control VrLook { get; private set; }

        protected override void FinishSetup()
        {
            base.FinishSetup();

            TouchLook = GetChildControl<Vector2Control>("TouchLook");
            VrMove = GetChildControl<Vector2Control>("VrMove");
            VrLook = GetChildControl<Vector2Control>("VrLook");
        }
    }
}
