// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : InGame

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>InGame の合成ルート。</summary>
    public sealed class InGameCompositor : UsefulToolkit.Initialization.GameCompositor<AutoGenerated.InGameCompositor>
    {
        [SerializeField] private Kizami.Initialization.MeleeCutInitializer _meleeCutInitializer;

        protected override void InjectAll()
        {
            // IInjectableを実装したInitializerはありません。
        }

        protected override void InitializeAll(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            if (_meleeCutInitializer != null) _meleeCutInitializer.Initialize(blackBoard);
        }
    }
}
