// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : InGame

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>InGame の合成ルート。</summary>
    public sealed class InGameCompositor : UsefulToolkit.Initialization.GameCompositor<AutoGenerated.InGameCompositor>
    {
        [SerializeField] private Kizami.Initialization.StandardPlayerInputRouteInitializer _standardPlayerInputRouteInitializer;
        [SerializeField] private Kizami.Initialization.EnemyInitializer _enemyInitializer;
        [SerializeField] private Kizami.Initialization.PlayerInitializer _playerInitializer;
        [SerializeField] private Kizami.Initialization.PlayerDebugInitializer _playerDebugInitializer;

        protected override void InjectAll()
        {
            if (_standardPlayerInputRouteInitializer != null)
            {
                {
                    if (TryGetContent<UsefulToolkit.BlackBoard.Input.IInputController>(out var dep0))
                    {
                        ((UsefulToolkit.Initialization.IInjectable<UsefulToolkit.BlackBoard.Input.IInputController>)_standardPlayerInputRouteInitializer).Inject(dep0);
                    }
                    else
                    {
                        UsefulToolkit.BlackBoard.Logger.UsefulLogger.LogWarning("依存の解決に失敗しました : StandardPlayerInputRouteInitializer (IInputController)", this);
                    }
                }
            }

            if (_playerDebugInitializer != null)
            {
                {
                    if (TryGetContent<Kizami.Application.PlayerHealthService>(out var dep0))
                    {
                        ((UsefulToolkit.Initialization.IInjectable<Kizami.Application.PlayerHealthService>)_playerDebugInitializer).Inject(dep0);
                    }
                    else
                    {
                        UsefulToolkit.BlackBoard.Logger.UsefulLogger.LogWarning("依存の解決に失敗しました : PlayerDebugInitializer (PlayerHealthService)", this);
                    }
                }
            }

        }

        protected override void InitializeAll(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            if (_standardPlayerInputRouteInitializer != null) _standardPlayerInputRouteInitializer.Initialize(blackBoard); // order: -70
            if (_enemyInitializer != null) _enemyInitializer.Initialize(blackBoard);
            if (_playerInitializer != null) _playerInitializer.Initialize(blackBoard);
            if (_playerDebugInitializer != null) _playerDebugInitializer.Initialize(blackBoard); // order: 10
        }
    }
}
