// UsefulToolkit が生成した Initializer のテンプレートです。
// 中身は自由に書き換えられます。再生成時、このファイルが既に存在する場合は上書きされません。
// 生成元シーン : UsefulToolkitPersistent

using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Input;
using UsefulToolkit.Initialization;

namespace AutoGenerated
{
    /// <summary>入力システムの初期化と、(map, action) の橋渡しを行う。</summary>
    public sealed class InputInitializer : InputInitializerBase
    {
        /// <summary>外部入力を仮想デバイス UsefulInputDevice へ書き込む橋渡しを返す。</summary>
        protected override IExternalInputDeviceBridge CreateExternalInputBridge() => new UsefulInputDeviceBridge();

        /// <param name="blackBoard">InputStateの登録先</param>
        public override void Initialize(IBlackBoard blackBoard)
        {
            base.Initialize(blackBoard);

            // (map, action) 単位の橋渡しと ActionMap の切り替えはビルドモードごとに異なるので、
            // インゲームのシーンの PlayerInputRouteInitializer が行う
        }

        private void Awake()
        {
            // 入力の操作面は BlackBoard に載せず、DI コンテナへ登録する
            UsefulToolkitPersistentCompositor.TryRegisterContent(Controller);
        }
    }
}
