// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : OutGame

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>OutGame の合成ルート。</summary>
    public sealed class OutGameCompositor : UsefulToolkit.Initialization.GameCompositor<AutoGenerated.OutGameCompositor>
    {
        [SerializeField] private Kizami.Initialization.OutGameStartInitializer _outGameStartInitializer;

        protected override void InjectAll()
        {
            if (_outGameStartInitializer != null)
            {
                {
                    if (TryGetContent<Kizami.Application.IGameSceneController>(out var dep0))
                    {
                        ((UsefulToolkit.Initialization.IInjectable<Kizami.Application.IGameSceneController>)_outGameStartInitializer).Inject(dep0);
                    }
                    else
                    {
                        UsefulToolkit.BlackBoard.Logger.UsefulLogger.LogWarning("依存の解決に失敗しました : OutGameStartInitializer (IGameSceneController)", this);
                    }
                }
            }

        }

        protected override void InitializeAll(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            if (_outGameStartInitializer != null) _outGameStartInitializer.Initialize(blackBoard);
        }
    }
}
