// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : StandardPlayerControl

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>StandardPlayerControl の合成ルート。</summary>
    public sealed class StandardPlayerControlCompositor : UsefulToolkit.Initialization.GameCompositor<AutoGenerated.StandardPlayerControlCompositor>
    {
        [SerializeField] private Kizami.Initialization.StandardPlayerInputRouteInitializer _standardPlayerInputRouteInitializer;
        [SerializeField] private Kizami.Initialization.PlayerInitializer _playerInitializer;

        protected override void InjectAll()
        {
            if (_standardPlayerInputRouteInitializer != null)
            {
                {
                    if (TryGetContent<UsefulToolkit.BlackBoard.Input.IInputController>(out var dep0))
                    {
                        ((UsefulToolkit.Initialization.IInjectable<UsefulToolkit.BlackBoard.Input.IInputController>)_standardPlayerInputRouteInitializer).Inject(dep0);
                    }
                    else
                    {
                        UsefulToolkit.BlackBoard.Logger.UsefulLogger.LogWarning("依存の解決に失敗しました : StandardPlayerInputRouteInitializer (IInputController)", this);
                    }
                }
            }

        }

        protected override void InitializeAll(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            if (_standardPlayerInputRouteInitializer != null) _standardPlayerInputRouteInitializer.Initialize(blackBoard); // order: -70
            if (_playerInitializer != null) _playerInitializer.Initialize(blackBoard);
        }
    }
}
