// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : UsefulToolkitPersistent

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>UsefulToolkitPersistent の合成ルート。</summary>
    public sealed class UsefulToolkitPersistentCompositor : UsefulToolkit.Initialization.RootGameCompositor<AutoGenerated.UsefulToolkitPersistentCompositor>
    {
        [SerializeField] private Kizami.Initialization.ApplicationManagementInitializer _applicationManagementInitializer;
        [SerializeField] private Kizami.Initialization.OperationSettingInitializer _operationSettingInitializer;
        [SerializeField] private Kizami.Initialization.TimeScaleInitializer _timeScaleInitializer;
        [SerializeField] private AutoGenerated.InputInitializer _inputInitializer;
        [SerializeField] private Kizami.Initialization.GameSceneInitializer _gameSceneInitializer;
        [SerializeField] private Kizami.Initialization.TimeScaleDebugInitializer _timeScaleDebugInitializer;

        protected override void RegisterChildBoards(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoardController blackBoardController)
        {
            blackBoardController.TryRegisterStateBoard(new Kizami.BlackBoard.AppBoard());
            blackBoardController.TryRegisterStateBoard(new Kizami.BlackBoard.PlayerBoard());
            blackBoardController.TryRegisterStateBoard(new UsefulToolkit.BlackBoard.Input.InputBoard());
            blackBoardController.TryRegisterStateBoard(new UsefulToolkit.BlackBoard.ProgramTools.PauseBoard());
        }

        protected override void InjectAll()
        {
            if (_timeScaleDebugInitializer != null)
            {
                {
                    if (TryGetContent<Kizami.Application.ITimeScaleController>(out var dep0))
                    {
                        ((UsefulToolkit.Initialization.IInjectable<Kizami.Application.ITimeScaleController>)_timeScaleDebugInitializer).Inject(dep0);
                    }
                    else
                    {
                        UsefulToolkit.BlackBoard.Logger.UsefulLogger.LogWarning("依存の解決に失敗しました : TimeScaleDebugInitializer (ITimeScaleController)", this);
                    }
                }
            }

        }

        protected override void InitializeAll(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            if (_applicationManagementInitializer != null) _applicationManagementInitializer.Initialize(blackBoard); // order: -90
            if (_operationSettingInitializer != null) _operationSettingInitializer.Initialize(blackBoard); // order: -90
            if (_timeScaleInitializer != null) _timeScaleInitializer.Initialize(blackBoard); // order: -90
            if (_inputInitializer != null) _inputInitializer.Initialize(blackBoard); // order: -80
            if (_gameSceneInitializer != null) _gameSceneInitializer.Initialize(blackBoard); // order: -70
            if (_timeScaleDebugInitializer != null) _timeScaleDebugInitializer.Initialize(blackBoard); // order: -70
        }
    }
}
