using AutoGenerated;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Logger;
using UsefulToolkit.Initialization;

namespace Kizami.Initialization
{
    /// <summary>
    /// このプロジェクトで使う入力アクションを IInputController へブリッジ登録する Initializer。
    /// InputState のチャンネルへ実際の入力値を流し込む経路をここで作る。
    /// </summary>
    public sealed class KizamiInputBindingInitializer : InputInitializerBase
    {
        public override void Initialize(IBlackBoard blackBoard)
        {
            base.Initialize(blackBoard);

            Controller.Bind<UnityEngine.Vector2>(ActionMaps.Player, PlayerActions.Move);
        }
    }
}
