using AutoGenerated;
using Kizami.BlackBoard;
using UsefulToolkit.Attributes;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Input;
using UsefulToolkit.BlackBoard.Logger;
using UsefulToolkit.Initialization;
using UsefulToolkit.Utility;

namespace Kizami.Initialization
{
    /// <summary>
    /// (Player, Move) / (Player, Look) チャンネルへ繋ぐ入力ソースを決める配線役の基底。
    /// 操作シーンへ置き、そのシーンの操作系に合った派生を使う。
    ///
    /// チャンネルは 3 ビルド共通で固定し、差し替えるのは入力ソースだけに留める。
    /// これにより Application 層（PlayerMovementService / PlayerLookService）は
    /// 操作系を知らずに済む。
    /// </summary>
    [InitializeOrder(InitializeOrderConst.Initializer)]
    public abstract class PlayerInputRouteInitializerBase : InitializerBase, IInjectable<IInputController>
    {
        /// <summary> 入力の操作面。Initialize より前に Compositor から注入される </summary>
        protected IInputController InputController { get; private set; }

        public void Inject(IInputController instance)
        {
            InputController = instance;
        }

        public override void Initialize(IBlackBoard blackBoard)
        {
            if (InputController == null)
            {
                UsefulLogger.LogError(
                    "IInputController が注入されていません。常駐シーンの InputInitializer が" +
                    "コンテナへ登録しているか確認してください。", this);
                base.Initialize(blackBoard);
                return;
            }

            if (!TryGetInputState(blackBoard, out var inputState))
            {
                base.Initialize(blackBoard);
                return;
            }

            ConnectInputSources(blackBoard, inputState);

            InputController.SwitchActionMap(ActionMaps.Player);

            base.Initialize(blackBoard);
        }

        /// <summary>
        /// この操作系の入力ソースを、移動・視点のチャンネルへ繋ぐ。
        /// </summary>
        /// <param name="blackBoard">追加で State が要る場合の取得元</param>
        /// <param name="inputState">入力の読み取り面</param>
        protected abstract void ConnectInputSources(IBlackBoard blackBoard, IInputState inputState);

        /// <summary>
        /// 現在のビルドモードを取得する。同じ操作シーンを複数のビルドモードで共用する派生だけが使う。
        /// </summary>
        /// <param name="blackBoard">IBuildModeState の取得元</param>
        /// <param name="buildMode">取得したビルドモード</param>
        /// <returns>取得できたか</returns>
        protected bool TryGetBuildMode(IBlackBoard blackBoard, out BuildMode buildMode)
        {
            buildMode = BuildMode.PC;

            if (!blackBoard.TryGetStateBoard<AppBoard>(out var appBoard))
            {
                UsefulLogger.LogError("AppBoard が未登録です。常駐シーンから Play しているか確認してください。", this);
                return false;
            }

            if (!appBoard.TryGetGameState<IBuildModeState>(out var buildModeState))
            {
                UsefulLogger.LogError(
                    "IBuildModeState が未登録です。ApplicationManagementInitializer の初期化順を確認してください。", this);
                return false;
            }

            buildMode = buildModeState.BuildMode;
            return true;
        }

        private bool TryGetInputState(IBlackBoard blackBoard, out IInputState inputState)
        {
            inputState = null;

            if (!blackBoard.TryGetStateBoard<InputBoard>(out var inputBoard))
            {
                UsefulLogger.LogError("InputBoard が未登録です。常駐シーンから Play しているか確認してください。", this);
                return false;
            }

            if (!inputBoard.TryGetGameState(out inputState))
            {
                UsefulLogger.LogError("IInputState が未登録です。InputInitializer の初期化順を確認してください。", this);
                return false;
            }

            return true;
        }
    }
}
