using AutoGenerated;
using UsefulToolkit.Attributes;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Input;
using UsefulToolkit.BlackBoard.Logger;
using UsefulToolkit.Initialization;
using UsefulToolkit.Utility;

namespace Kizami.Initialization
{
    /// <summary>
    /// (Player, Move) / (Player, Look) チャンネルへ繋ぐ入力ソースを決める配線役の基底。
    /// インゲームのシーンへ置き、操作系に合った派生を使う。
    /// チャンネルは 3 ビルド共通で固定し、差し替えるのは入力ソースだけにする。
    /// </summary>
    [InitializeOrder(InitializeOrderConst.Initializer)]
    public abstract class PlayerInputRouteInitializerBase : InitializerBase, IInjectable<IInputController>
    {
        /// <summary> 入力の操作面。Initialize より前に Compositor から注入される </summary>
        protected IInputController InputController { get; private set; }

        public void Inject(IInputController instance)
        {
            InputController = instance;
        }

        public override void Initialize(IBlackBoard blackBoard)
        {
            if (InputController == null)
            {
                UsefulLogger.LogError(
                    "IInputController が注入されていません。常駐シーンの InputInitializer が" +
                    "コンテナへ登録しているか確認してください。", this);
                base.Initialize(blackBoard);
                return;
            }

            ConnectInputSources(blackBoard);

            InputController.SwitchActionMap(ActionMaps.Player);

            base.Initialize(blackBoard);
        }

        /// <summary>
        /// この操作系の入力ソースを、移動・視点のチャンネルへ繋ぐ。
        /// </summary>
        /// <param name="blackBoard">入力ソースが State を取得する取得元</param>
        protected abstract void ConnectInputSources(IBlackBoard blackBoard);
    }
}
