using AutoGenerated;
using Kizami.BlackBoard;
using UnityEngine;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Input;
using UsefulToolkit.EngineAdapter.Input;

namespace Kizami.Initialization
{
    /// <summary>
    /// PC とスマホが共用する操作シーンの入力配線。
    ///
    /// 移動はどちらも InputAction 直結でよい。スマホの移動スティックは
    /// On-Screen Controls が InputAction を焚く為、PC と同じ配線で通る。
    /// 視点だけが経路として分かれる（PC はマウス、スマホは画面ドラッグ）ので、
    /// そこだけをビルドモードで差し替える。
    /// </summary>
    public sealed class StandardPlayerInputRouteInitializer : PlayerInputRouteInitializerBase
    {
        [SerializeField]
        [Tooltip("画面ドラッグで視点を操作する入力ソース。使わないビルドモードの枠は空にする。")]
        private BuildModeSelector<MobileInputEngineAdapter> _touchLookSource = new();

        [SerializeField]
        [Tooltip("有効にする操作用 UI のルート。使わないビルドモードの枠は空にする。")]
        private BuildModeSelector<GameObject> _controlUiRoot = new();

        protected override void ConnectInputSources(IBlackBoard blackBoard, IInputState inputState)
        {
            InputController.Bind<Vector2>(ActionMaps.Player, PlayerActions.Move);

            if (!TryGetBuildMode(blackBoard, out var buildMode)) return;

            SetUpLook(_touchLookSource.Select(buildMode), inputState);
            ActivateControlUi(_controlUiRoot.Select(buildMode));
        }

        /// <summary>
        /// 視点操作の入力ソースを繋ぐ。
        /// 画面ドラッグの入力ソースが指定されていなければ、InputAction を直接繋ぐ。
        /// </summary>
        /// <param name="touchLookSource">画面ドラッグの入力ソース。無ければ null</param>
        /// <param name="inputState">入力の読み取り面</param>
        private void SetUpLook(MobileInputEngineAdapter touchLookSource, IInputState inputState)
        {
            if (touchLookSource == null)
            {
                InputController.Bind<Vector2>(ActionMaps.Player, PlayerActions.Look);
                return;
            }

            touchLookSource.SetInput(inputState, InputController);
            touchLookSource.Bind(ActionMaps.Player, PlayerActions.Look);
            touchLookSource.Initialize();
        }

        /// <summary>
        /// 操作用 UI を有効にする。指定が無ければ何もしない。
        /// </summary>
        /// <param name="controlUiRoot">有効にする UI のルート。無ければ null</param>
        private void ActivateControlUi(GameObject controlUiRoot)
        {
            if (controlUiRoot == null) return;

            controlUiRoot.SetActive(true);
        }
    }
}
