using AutoGenerated;
using Kizami.BlackBoard;
using Kizami.EngineAdapter;
using UnityEngine;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Input;

namespace Kizami.Initialization
{
    /// <summary>
    /// PC とスマホが共用する操作シーンの入力配線。
    ///
    /// 移動・視点はどちらも InputAction がそのまま Application へ届く。スマホの移動スティックは
    /// On-Screen Controls が InputAction を焚く為、PC と同じ経路で通る。
    /// スマホの画面ドラッグによる視点操作だけは TouchLookInputSource が外部入力スロット
    /// (ExternalInputs.TouchLook) へ書き込み、Player/Look にバインドされたスロット経由で届く。
    /// その入力ソースをビルドモードで差し替える。
    /// </summary>
    public sealed class StandardPlayerInputRouteInitializer : PlayerInputRouteInitializerBase
    {
        [SerializeField]
        [Tooltip("画面ドラッグで視点を操作する入力ソース。使わないビルドモードの枠は空にする。")]
        private BuildModeSelector<TouchLookInputSource> _touchLookSource = new();

        [SerializeField]
        [Tooltip("有効にする操作用 UI のルート。使わないビルドモードの枠は空にする。")]
        private BuildModeSelector<GameObject> _controlUiRoot = new();

        protected override void ConnectInputSources(IBlackBoard blackBoard, IInputState inputState)
        {
            if (!TryGetBuildMode(blackBoard, out var buildMode)) return;

            SetUpTouchLook(_touchLookSource.Select(buildMode), inputState);
            ActivateControlUi(_controlUiRoot.Select(buildMode));
        }

        /// <summary>
        /// 画面ドラッグの入力ソースを、視点操作の外部入力スロットへ繋ぐ。指定が無ければ何もしない。
        /// </summary>
        /// <param name="touchLookSource">画面ドラッグの入力ソース。無ければ null</param>
        /// <param name="inputState">入力の読み取り面</param>
        private void SetUpTouchLook(TouchLookInputSource touchLookSource, IInputState inputState)
        {
            if (touchLookSource == null) return;

            touchLookSource.SetInput(inputState, InputController);
            touchLookSource.Bind(ActionMaps.Player, ExternalInputs.TouchLook);
            touchLookSource.Initialize();
        }

        /// <summary>
        /// 操作用 UI を有効にする。指定が無ければ何もしない。
        /// </summary>
        /// <param name="controlUiRoot">有効にする UI のルート。無ければ null</param>
        private void ActivateControlUi(GameObject controlUiRoot)
        {
            if (controlUiRoot == null) return;

            controlUiRoot.SetActive(true);
        }
    }
}
