using AutoGenerated;
using Kizami.EngineAdapter;
using UnityEngine;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Input;
using UsefulToolkit.BlackBoard.Logger;

namespace Kizami.Initialization
{
    /// <summary>
    /// VR の操作シーンの入力配線。VR 専用シーンにしか置かれない為、ビルドモードは参照しない。
    ///
    /// 移動・視点ともに VRControllers のスティックをポーリングで読み、Player のチャンネルへ流す。
    /// InputAction の started / canceled を購読しないのは、XR デバイスのスティックでは
    /// 入力を継続していてもそれらが繰り返し発火する為。
    /// </summary>
    public sealed class VrPlayerInputRouteInitializer : PlayerInputRouteInitializerBase
    {
        [SerializeField]
        [Tooltip("左手スティックを移動として読む入力ソース。")]
        private PollingStickInputSource _moveSource;

        [SerializeField]
        [Tooltip("右手スティックを旋回として読む入力ソース。")]
        private PollingStickInputSource _lookSource;

        protected override void ConnectInputSources(IBlackBoard blackBoard, IInputState inputState)
        {
            SetUpSource(_moveSource, inputState, VRControllersActions.Move, PlayerActions.Move,
                ignoreVertical: false);

            // 上下方向は HMD の姿勢が担う為、旋回の入力からは落とす
            SetUpSource(_lookSource, inputState, VRControllersActions.Look, PlayerActions.Look,
                ignoreVertical: true);
        }

        /// <param name="source">配線する入力ソース</param>
        /// <param name="inputState">入力の読み取り面</param>
        /// <param name="sourceAction">読み出し元の VRControllers の Action</param>
        /// <param name="destinationAction">流し込み先の Player の Action</param>
        /// <param name="ignoreVertical">縦方向の入力を捨てるか</param>
        private void SetUpSource(PollingStickInputSource source, IInputState inputState,
            VRControllersActions sourceAction, PlayerActions destinationAction, bool ignoreVertical)
        {
            if (source == null)
            {
                UsefulLogger.LogError(
                    $"PollingStickInputSource が設定されていない為、[{destinationAction}] を繋げません。", this);
                return;
            }

            source.SetInput(inputState, InputController);
            source.Bind(ActionMaps.VRControllers, sourceAction, ActionMaps.Player, destinationAction,
                ignoreVertical);
            source.Initialize();
        }
    }
}
