using AutoGenerated;
using Kizami.EngineAdapter;
using UnityEngine;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Logger;

namespace Kizami.Initialization
{
    /// <summary>
    /// VR の操作系の入力配線。
    /// XR デバイスのスティックは入力を継続していても started / canceled が繰り返し発火するので、
    /// 移動・視点ともに VRControllers のスティックをポーリングで読み、外部入力スロット（ExternalInputs.VrMove / VrLook）へ書き込む。
    /// </summary>
    public sealed class VrPlayerInputRouteInitializer : PlayerInputRouteInitializerBase
    {
        [SerializeField]
        [Tooltip("左手スティックを移動として読む入力ソース。")]
        private PollingStickInputSource _moveSource;

        [SerializeField]
        [Tooltip("右手スティックを旋回として読む入力ソース。")]
        private PollingStickInputSource _lookSource;

        protected override void ConnectInputSources(IBlackBoard blackBoard)
        {
            SetUpSource(_moveSource, blackBoard, VRControllersActions.Move, ExternalInputs.VrMove,
                ignoreVertical: false);

            // 上下方向は HMD の姿勢が担う為、旋回の入力からは落とす
            SetUpSource(_lookSource, blackBoard, VRControllersActions.Look, ExternalInputs.VrLook,
                ignoreVertical: true);
        }

        /// <param name="source">配線する入力ソース</param>
        /// <param name="blackBoard">入力ソースが State を取得する取得元</param>
        /// <param name="sourceAction">読み出し元の VRControllers の Action</param>
        /// <param name="destinationSlot">書き込み先の外部入力スロット</param>
        /// <param name="ignoreVertical">縦方向の入力を捨てるか</param>
        private void SetUpSource(PollingStickInputSource source, IBlackBoard blackBoard,
            VRControllersActions sourceAction, ExternalInputs destinationSlot, bool ignoreVertical)
        {
            if (source == null)
            {
                UsefulLogger.LogError(
                    $"PollingStickInputSource が設定されていない為、[{destinationSlot}] を繋げません。", this);
                return;
            }

            source.Initialize(blackBoard, InputController, ActionMaps.VRControllers, sourceAction, ActionMaps.Player,
                destinationSlot, ignoreVertical);
        }
    }
}
