using System;
using System.Collections.Generic;
using AutoGenerated;
using Kizami.BlackBoard;
using Kizami.External;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Input;

namespace Kizami.Application
{
    /// <summary>
    /// 投擲とランチャーの入力を受けて、かけらをつかむ・投げる・装填する・撃つ要求を実行役へ伝えるユースケース。
    /// 投擲の入力を押したときにつかみ、離したときに投げる。
    /// つかむのと装填するのはスローモード中だけで、持ったかけらと装填したかけらはスローモードが終わっても投げる・撃つことができる。
    /// </summary>
    public sealed class FragmentThrowService : IDisposable
    {
        private readonly PlayerParameterData _parameters;
        private readonly Func<float, float, bool> _tryGrab;
        private readonly Action<float> _onThrow;
        private readonly Func<bool> _tryLoad;
        private readonly Action<float> _onFire;
        private readonly ISlowModeState _slowModeState;
        private readonly List<IDisposable> _subscriptions = new();

        /// <param name="blackBoard">入力とスローモードの状態の取得元</param>
        /// <param name="parameters">つかむ範囲と、投げる速さ・撃つ速さの取得元</param>
        /// <param name="tryGrab">かけらをつかむ関数。引数はつかむ距離（m）と半径（m）。つかめたら true</param>
        /// <param name="onThrow">持っているかけらを投げる関数。引数は初速（m/s）</param>
        /// <param name="tryLoad">持っているかけらをランチャーに装填する関数。装填できたら true</param>
        /// <param name="onFire">装填したかけらを撃つ関数。引数は速さ（m/s）</param>
        public FragmentThrowService(IBlackBoard blackBoard, PlayerParameterData parameters,
            Func<float, float, bool> tryGrab, Action<float> onThrow, Func<bool> tryLoad, Action<float> onFire)
        {
            _parameters = parameters;
            _tryGrab = tryGrab;
            _onThrow = onThrow;
            _tryLoad = tryLoad;
            _onFire = onFire;

            if (!blackBoard.TryGetGameState<InputBoard, IInputState>(out var inputState, this) ||
                !blackBoard.TryGetSceneState<PlayerBoard, ISlowModeState>(out _slowModeState, this)) return;

            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.Throw, OnThrow));
            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.LoadLauncher,
                OnLoadLauncher));
            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.FireLauncher,
                OnFireLauncher));
        }

        private void OnThrow(InputContext<float> context)
        {
            switch (context.Phase)
            {
                case InputPhase.Performed:
                    if (_slowModeState.IsActive) _tryGrab?.Invoke(_parameters.GrabRange, _parameters.GrabRadius);
                    break;
                case InputPhase.Canceled:
                    _onThrow?.Invoke(_parameters.ThrowSpeed);
                    break;
            }
        }

        private void OnLoadLauncher(InputContext<float> context)
        {
            if (context.Phase != InputPhase.Performed || !_slowModeState.IsActive) return;

            _tryLoad?.Invoke();
        }

        private void OnFireLauncher(InputContext<float> context)
        {
            if (context.Phase != InputPhase.Performed) return;

            _onFire?.Invoke(_parameters.LauncherSpeed);
        }

        public void Dispose()
        {
            foreach (var subscription in _subscriptions)
            {
                subscription.Dispose();
            }

            _subscriptions.Clear();
        }
    }
}
