using System;
using System.Collections.Generic;
using AutoGenerated;
using Kizami.BlackBoard;
using Kizami.External;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Input;

namespace Kizami.Application
{
    /// <summary>
    /// 投擲の入力を受けて、かけらをつかむ・投げる要求を実行役へ伝えるユースケース。
    /// 入力を押したときにつかみ、離したときに投げる。つかめるのはスローモード中だけで、持ったかけらはスローモードが終わっても投げられる。
    /// </summary>
    public sealed class FragmentThrowService : IDisposable
    {
        private readonly PlayerParameterData _parameters;
        private readonly Func<float, float, bool> _tryGrab;
        private readonly Action<float> _onThrow;
        private readonly ISlowModeState _slowModeState;
        private readonly List<IDisposable> _subscriptions = new();

        /// <param name="blackBoard">入力とスローモードの状態の取得元</param>
        /// <param name="parameters">つかむ範囲と投げる速さの取得元</param>
        /// <param name="tryGrab">かけらをつかむ関数。引数はつかむ距離（m）と半径（m）。つかめたら true</param>
        /// <param name="onThrow">持っているかけらを投げる関数。引数は初速（m/s）</param>
        public FragmentThrowService(IBlackBoard blackBoard, PlayerParameterData parameters,
            Func<float, float, bool> tryGrab, Action<float> onThrow)
        {
            _parameters = parameters;
            _tryGrab = tryGrab;
            _onThrow = onThrow;

            if (!blackBoard.TryGetGameState<InputBoard, IInputState>(out var inputState, this) ||
                !blackBoard.TryGetSceneState<PlayerBoard, ISlowModeState>(out _slowModeState, this)) return;

            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.Throw, OnThrow));
        }

        private void OnThrow(InputContext<float> context)
        {
            switch (context.Phase)
            {
                case InputPhase.Performed:
                    if (_slowModeState.IsActive) _tryGrab?.Invoke(_parameters.GrabRange, _parameters.GrabRadius);
                    break;
                case InputPhase.Canceled:
                    _onThrow?.Invoke(_parameters.ThrowSpeed);
                    break;
            }
        }

        public void Dispose()
        {
            foreach (var subscription in _subscriptions)
            {
                subscription.Dispose();
            }

            _subscriptions.Clear();
        }
    }
}
