using System;
using System.Collections.Generic;
using AutoGenerated;
using Kizami.BlackBoard;
using Kizami.External;
using UnityEngine;
using UsefulToolkit.BlackBoard.Input;

namespace Kizami.Application
{
    /// <summary>
    /// 近接切断の入力を解釈して MeleeCutState へ書き込み、振ったことを切断の実行役へ伝えるユースケース。
    /// MeleeCutState の具象インスタンスはこのクラスだけが保持する（Single Writer）。
    /// 切断面の回転入力 1 回ごとに、アクセシビリティの設定にある角度だけ切断面を回す。
    /// 攻撃入力は、前回振ってから攻撃間隔が経っていれば、そのときの角度で振ったときの関数を呼ぶ。
    /// </summary>
    public sealed class MeleeCutService : IDisposable
    {
        /// <summary> 切断面の角度の範囲（度）。180 度回すと同じ面になる </summary>
        private const float AngleRange = 180f;

        private readonly MeleeCutState _state = new();
        private readonly IAccessibilitySettingState _accessibilitySettingState;
        private readonly PlayerParameterData _parameters;
        private readonly Func<double> _getUnscaledTime;
        private readonly Action<float> _onSwing;
        private readonly List<IDisposable> _subscriptions = new();

        /// <summary> 前回振った時刻（unscaled の秒） </summary>
        private double _lastSwingTime = double.NegativeInfinity;

        /// <param name="playerBoard">MeleeCutState の登録先</param>
        /// <param name="inputState">切断面の回転入力と攻撃入力の取得元</param>
        /// <param name="accessibilitySettingState">回転入力 1 回あたりの回転角度の取得元</param>
        /// <param name="parameters">攻撃間隔の取得元</param>
        /// <param name="getUnscaledTime">スローモードの影響を受けない現在の時刻（秒）を返す関数</param>
        /// <param name="onSwing">振ったときに呼ぶ関数。引数は振ったときの切断面の角度（度）</param>
        /// <param name="sceneId">State を紐づけるシーンのビルドインデックス</param>
        public MeleeCutService(PlayerBoard playerBoard, IInputState inputState,
            IAccessibilitySettingState accessibilitySettingState, PlayerParameterData parameters,
            Func<double> getUnscaledTime, Action<float> onSwing, int sceneId)
        {
            _accessibilitySettingState = accessibilitySettingState;
            _parameters = parameters;
            _getUnscaledTime = getUnscaledTime;
            _onSwing = onSwing;

            playerBoard.RegisterSceneState<IMeleeCutState>(_state, sceneId);

            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.CutRotate, OnCutRotate));
            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.Attack, OnAttack));
        }

        /// <summary>
        /// 回転入力の符号の向きへ、1 回分の角度だけ切断面を回す。正の入力（ホイールを上へ回す）で角度が増える。
        /// </summary>
        private void OnCutRotate(InputContext<float> context)
        {
            if (context.Phase != InputPhase.Performed || context.Value == 0f) return;

            var step = Mathf.Sign(context.Value) * _accessibilitySettingState.CutRotateStepAngle;
            _state.SetAngle(Mathf.Repeat(_state.Angle + step, AngleRange));
        }

        /// <summary>
        /// 前回振ってから攻撃間隔が経っていれば、今の角度で振ったときの関数を呼ぶ。間隔内の入力は捨てる。
        /// </summary>
        private void OnAttack(InputContext<float> context)
        {
            if (context.Phase != InputPhase.Performed) return;

            var now = _getUnscaledTime();
            if (now - _lastSwingTime < _parameters.MeleeAttackInterval) return;

            _lastSwingTime = now;
            _onSwing?.Invoke(_state.Angle);
        }

        public void Dispose()
        {
            foreach (var subscription in _subscriptions)
            {
                subscription.Dispose();
            }

            _subscriptions.Clear();
        }
    }
}
