using System;
using System.Collections.Generic;
using AutoGenerated;
using Kizami.BlackBoard;
using UnityEngine;
using UsefulToolkit.BlackBoard.Input;

namespace Kizami.Application
{
    /// <summary>
    /// 近接切断の入力を解釈して MeleeCutState へ書き込むユースケース。
    /// MeleeCutState の具象インスタンスはこのクラスだけが保持する（Single Writer）。
    /// 切断面の回転入力 1 回ごとに、アクセシビリティの設定にある角度だけ切断面を回す。
    /// </summary>
    public sealed class MeleeCutService : IDisposable
    {
        /// <summary> 切断面の角度の範囲（度）。180 度回すと同じ面になる </summary>
        private const float AngleRange = 180f;

        private readonly MeleeCutState _state = new();
        private readonly IAccessibilitySettingState _accessibilitySettingState;
        private readonly List<IDisposable> _subscriptions = new();

        /// <param name="playerBoard">MeleeCutState の登録先</param>
        /// <param name="inputState">切断面の回転入力の取得元</param>
        /// <param name="accessibilitySettingState">回転入力 1 回あたりの回転角度の取得元</param>
        /// <param name="sceneId">State を紐づけるシーンのビルドインデックス</param>
        public MeleeCutService(PlayerBoard playerBoard, IInputState inputState,
            IAccessibilitySettingState accessibilitySettingState, int sceneId)
        {
            _accessibilitySettingState = accessibilitySettingState;

            playerBoard.RegisterSceneState<IMeleeCutState>(_state, sceneId);

            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.CutRotate, OnCutRotate));
        }

        /// <summary>
        /// 回転入力の符号の向きへ、1 回分の角度だけ切断面を回す。正の入力（ホイールを上へ回す）で角度が増える。
        /// </summary>
        private void OnCutRotate(InputContext<float> context)
        {
            if (context.Phase != InputPhase.Performed || context.Value == 0f) return;

            var step = Mathf.Sign(context.Value) * _accessibilitySettingState.CutRotateStepAngle;
            _state.SetAngle(Mathf.Repeat(_state.Angle + step, AngleRange));
        }

        public void Dispose()
        {
            foreach (var subscription in _subscriptions)
            {
                subscription.Dispose();
            }

            _subscriptions.Clear();
        }
    }
}
