using System;
using System.Collections.Generic;
using AutoGenerated;
using Kizami.BlackBoard;
using Kizami.External;
using UnityEngine;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Input;

namespace Kizami.Application
{
    /// <summary>
    /// 近接切断の入力を解釈して MeleeCutState へ書き込み、振ったことを切断の実行役へ伝えるユースケース。
    /// </summary>
    public sealed class MeleeCutService : IDisposable
    {
        /// <summary> 切断面の角度の範囲（度）。180 度回すと同じ面になる </summary>
        private const float ANGLE_RANGE = 180f;

        private readonly MeleeCutState _state = new();
        private readonly IOperationSettingState _settingState;
        private readonly PlayerParameterData _parameters;
        private readonly Action<float> _onSwing;
        private readonly List<IDisposable> _subscriptions = new();

        /// <summary> 前回振った時刻（unscaled の秒） </summary>
        private double _lastSwingTime = double.NegativeInfinity;

        /// <param name="blackBoard">MeleeCutState の登録先と、入力・回転角度の設定の取得元</param>
        /// <param name="parameters">攻撃間隔の取得元</param>
        /// <param name="onSwing">振ったときに呼ぶ関数。引数は振ったときの切断面の角度（度）</param>
        /// <param name="sceneId">State を紐づけるシーンのビルドインデックス</param>
        public MeleeCutService(IBlackBoard blackBoard, PlayerParameterData parameters, Action<float> onSwing,
            int sceneId)
        {
            _parameters = parameters;
            _onSwing = onSwing;

            if (!blackBoard.TryGetBoard<PlayerBoard>(out var playerBoard, this) ||
                !blackBoard.TryGetGameState<InputBoard, IInputState>(out var inputState, this) ||
                !blackBoard.TryGetGameState<AppBoard, IOperationSettingState>(out _settingState, this)) return;

            playerBoard.RegisterSceneState<IMeleeCutState>(_state, sceneId);

            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.CutRotate, OnCutRotate));
            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.Attack, OnAttack));
        }

        /// <summary>
        /// 回転入力の符号の向きへ、1 回分の角度だけ切断面を回す。正の入力（ホイールを上へ回す）で角度が増える。
        /// </summary>
        private void OnCutRotate(InputContext<float> context)
        {
            if (context.Phase != InputPhase.Performed || context.Value == 0f) return;

            var step = Mathf.Sign(context.Value) * _settingState.CutRotateStepAngle;
            _state.SetAngle(Mathf.Repeat(_state.Angle + step, ANGLE_RANGE));
        }

        /// <summary>
        /// 前回振ってから攻撃間隔が経っていれば、今の角度で振ったときの関数を呼ぶ。間隔内の入力は捨てる。
        /// </summary>
        private void OnAttack(InputContext<float> context)
        {
            if (context.Phase != InputPhase.Performed) return;

            // スローモード中も攻撃間隔は実時間で数える
            var now = Time.unscaledTimeAsDouble;
            if (now - _lastSwingTime < _parameters.MeleeAttackInterval) return;

            _lastSwingTime = now;
            _onSwing?.Invoke(_state.Angle);
        }

        public void Dispose()
        {
            foreach (var subscription in _subscriptions)
            {
                subscription.Dispose();
            }

            _subscriptions.Clear();
        }
    }
}
