using System;
using System.Collections.Generic;
using AutoGenerated;
using Kizami.BlackBoard;
using UnityEngine;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Input;

namespace Kizami.Application
{
    /// <summary>
    /// 視点入力に感度倍率を掛けて PlayerLookState へ書き込むユースケース。入力イベントごとに State を更新する。
    /// </summary>
    public sealed class PlayerLookService : IDisposable
    {
        private readonly PlayerLookState _state = new();
        private readonly IOperationSettingState _settingState;
        private readonly List<IDisposable> _subscriptions = new();

        /// <param name="blackBoard">PlayerLookState の登録先と、視点入力・感度倍率の取得元</param>
        /// <param name="sceneId">State を紐づけるシーンのビルドインデックス</param>
        public PlayerLookService(IBlackBoard blackBoard, int sceneId)
        {
            if (!blackBoard.TryGetBoard<PlayerBoard>(out var playerBoard, this) ||
                !blackBoard.TryGetGameState<InputBoard, IInputState>(out var inputState, this) ||
                !blackBoard.TryGetGameState<AppBoard, IOperationSettingState>(out _settingState, this)) return;

            playerBoard.RegisterSceneState<IPlayerLookState>(_state, sceneId);

            _subscriptions.Add(inputState.RegisterInput<Vector2>(ActionMaps.Player, PlayerActions.Look, OnLook));
        }

        private void OnLook(InputContext<Vector2> context)
        {
            if (context.Phase == InputPhase.Canceled)
            {
                _state.SetLookInput(Vector2.zero);
                return;
            }

            var raw = context.Value;

            // 入力の右方向・上方向を、そのまま視点の右回り・上向きとして扱う
            _state.SetLookInput(new Vector2(
                raw.x * _settingState.HorizontalSensitivity,
                raw.y * _settingState.VerticalSensitivity));
        }

        public void Dispose()
        {
            foreach (var subscription in _subscriptions)
            {
                subscription.Dispose();
            }

            _subscriptions.Clear();
        }
    }
}
