using System;
using System.Collections.Generic;
using AutoGenerated;
using Kizami.BlackBoard;
using Kizami.External;
using UnityEngine;
using UsefulToolkit.BlackBoard.Input;

namespace Kizami.Application
{
    /// <summary>
    /// 入力と視線の向きから、プレイヤーのワールド空間の目標速度を決めて PlayerMovementState に書き込むユースケース。
    /// PlayerMovementState の具象インスタンスはこのクラスだけが保持する（Single Writer）。
    /// 入力イベントでは入力値を記録するだけで、State の更新は Step（EngineAdapterLayer の FixedUpdate から直接配線で呼ばれる）で行う。
    /// 物理への反映と加減速の補間は EngineAdapterLayer 側（PlayerMovementAdapterBase）が行う。
    /// </summary>
    public sealed class PlayerMovementService : IDisposable
    {
        private readonly PlayerMovementState _state = new();
        private readonly IAccessibilitySettingState _accessibilitySettingState;
        private readonly PlayerParameterData _parameters;
        private readonly List<IDisposable> _subscriptions = new();

        /// <summary> 移動入力。x が右、y が前を正とし、長さは 1 以下 </summary>
        private Vector2 _moveInput;

        private bool _isSprintHeld;
        private bool _isSprintToggled;

        /// <summary> 視線の向きを水平面へ投影した向き。視線が真上・真下を向いている間は直前の値を保つ </summary>
        private Vector3 _viewForward = Vector3.forward;

        /// <param name="playerBoard">PlayerMovementState の登録先</param>
        /// <param name="inputState">移動・ダッシュ入力の取得元</param>
        /// <param name="accessibilitySettingState">ダッシュ入力の受け付け方の取得元</param>
        /// <param name="parameters">移動のパラメータ</param>
        /// <param name="sceneId">State を紐づけるシーンのビルドインデックス</param>
        public PlayerMovementService(PlayerBoard playerBoard, IInputState inputState,
            IAccessibilitySettingState accessibilitySettingState, PlayerParameterData parameters, int sceneId)
        {
            _accessibilitySettingState = accessibilitySettingState;
            _parameters = parameters;

            playerBoard.RegisterSceneState<IPlayerMovementState>(_state, sceneId);

            _subscriptions.Add(inputState.RegisterInput<Vector2>(ActionMaps.Player, PlayerActions.Move, OnMove));
            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.Sprint, OnSprint));
        }

        /// <summary>ダッシュ中かどうか。ダッシュ入力の受け付け方に応じて、押下中またはトグルの状態を返す。</summary>
        private bool IsSprinting => _accessibilitySettingState.SprintInputMode == SprintInputMode.Hold
            ? _isSprintHeld
            : _isSprintToggled;

        /// <summary>
        /// 物理の 1 ステップごとに呼ばれ、記録済みの入力と視線の向きから目標速度を State に書き込む。
        /// </summary>
        /// <param name="viewDirection">ワールド空間の視線の向き</param>
        public void Step(Vector3 viewDirection)
        {
            UpdateViewForward(viewDirection);

            var speed = IsSprinting ? _parameters.SprintSpeed : _parameters.WalkSpeed;
            _state.SetTargetVelocity(ToWorldDirection(_moveInput) * speed);
        }

        private void OnMove(InputContext<Vector2> context)
        {
            _moveInput = context.Phase == InputPhase.Canceled
                ? Vector2.zero
                : Vector2.ClampMagnitude(context.Value, 1f);

            if (_moveInput.sqrMagnitude <= Mathf.Epsilon)
            {
                _isSprintToggled = false;
            }
        }

        private void OnSprint(InputContext<float> context)
        {
            switch (context.Phase)
            {
                case InputPhase.Performed:
                    _isSprintHeld = true;
                    _isSprintToggled = !_isSprintToggled;
                    break;
                case InputPhase.Canceled:
                    _isSprintHeld = false;
                    break;
            }
        }

        /// <summary>
        /// 視線の向きを水平面へ投影して保持する。水平成分がほぼ無いときは更新しない。
        /// </summary>
        private void UpdateViewForward(Vector3 viewDirection)
        {
            viewDirection.y = 0f;
            if (viewDirection.sqrMagnitude < 1e-6f) return;

            _viewForward = viewDirection.normalized;
        }

        /// <summary>
        /// 入力（x が右、y が前）を、水平な視線の向きを前方としたワールド方向へ変換する。長さは入力の長さを保つ。
        /// </summary>
        private Vector3 ToWorldDirection(Vector2 input)
        {
            var right = Vector3.Cross(Vector3.up, _viewForward);
            return right * input.x + _viewForward * input.y;
        }

        public void Dispose()
        {
            foreach (var subscription in _subscriptions)
            {
                subscription.Dispose();
            }

            _subscriptions.Clear();
        }
    }
}
