using System;
using System.Collections.Generic;
using AutoGenerated;
using Kizami.BlackBoard;
using UnityEngine;
using UsefulToolkit.BlackBoard.Input;

namespace Kizami.Application
{
    /// <summary>
    /// 視点入力を解釈して PlayerLookState へ書き込むユースケース。
    /// PlayerLookState の具象インスタンスはこのクラスだけが保持する（Single Writer）。
    /// 毎フレーム処理は持たず、入力イベントに反応して State を更新するだけ。
    ///
    /// ここで行うのは「入力をどちら向きの回転として扱うか」と感度倍率の適用まで。
    /// 実際に何度回すか、上下方向を使うかどうかは EngineAdapterLayer 側が決める。
    /// </summary>
    public sealed class PlayerLookService : IDisposable
    {
        private readonly PlayerLookState _state = new();
        private readonly IPlayerOperationConfigState _configState;
        private readonly List<IDisposable> _subscriptions = new();

        /// <param name="playerBoard">PlayerLookState の登録先</param>
        /// <param name="inputState">視点入力の取得元</param>
        /// <param name="configState">感度倍率の取得元</param>
        /// <param name="sceneId">State を紐づけるシーンのビルドインデックス</param>
        public PlayerLookService(PlayerBoard playerBoard, IInputState inputState,
            IPlayerOperationConfigState configState, int sceneId)
        {
            _configState = configState;

            playerBoard.RegisterSceneState<IPlayerLookState>(_state, sceneId);

            _subscriptions.Add(inputState.RegisterInput<Vector2>(ActionMaps.Player, PlayerActions.Look, OnLook));
        }

        private void OnLook(InputContext<Vector2> context)
        {
            if (context.Phase == InputPhase.Canceled)
            {
                _state.ChangeLookInput(Vector2.zero);
                return;
            }

            var raw = context.Value;

            // 入力の右方向・上方向を、そのまま視点の右回り・上向きとして扱う
            _state.ChangeLookInput(new Vector2(
                raw.x * _configState.HorizontalSensitivity,
                raw.y * _configState.VerticalSensitivity));
        }

        public void Dispose()
        {
            foreach (var subscription in _subscriptions)
            {
                subscription.Dispose();
            }

            _subscriptions.Clear();
        }
    }
}
