using System;
using System.Collections.Generic;
using AutoGenerated;
using Kizami.BlackBoard;
using Kizami.External;
using UnityEngine;
using UsefulToolkit.BlackBoard.Input;

namespace Kizami.Application
{
    /// <summary>
    /// 入力と視線の向き、触れている物から、プレイヤーの移動モード・ワールド空間の目標速度・ジャンプを決めるユースケース。
    /// 入力イベントでは入力値を記録し、判定と State の更新は Step で行う。
    /// 物理への反映と加減速の補間は PlayerMovementAdapterBase が行う。
    /// </summary>
    public sealed class PlayerMovementService : IDisposable
    {
        private readonly PlayerMovementState _state = new();
        private readonly IOperationSettingState _settingState;
        private readonly PlayerParameterData _parameters;
        private readonly List<IDisposable> _subscriptions = new();
        private readonly IDisposable _contactStateWaiter;

        private IPlayerContactState _contactState;

        /// <summary> 移動入力。x が右、y が前を正とし、長さは 1 以下 </summary>
        private Vector2 _moveInput;

        private bool _isSprintHeld;
        private bool _isSprintToggled;

        /// <summary> 次の Step で処理するジャンプ入力があるか </summary>
        private bool _isJumpRequested;

        /// <summary> 視線の向きを水平面へ投影した向き。視線が真上・真下を向いている間は直前の値を保つ </summary>
        private Vector3 _viewForward = Vector3.forward;

        /// <summary> 壁走りの残りの持ち時間（秒）。着地で最大値に戻る </summary>
        private float _wallRunTimeRemaining;

        /// <summary> 壁から離れようとする入力が続いている時間（秒） </summary>
        private float _wallDetachInputTime;

        /// <summary> 壁ジャンプ後、壁との接触が一度切れるまで true になり、その間は壁走りへの再突入を止める </summary>
        private bool _isWaitingWallRelease;

        /// <summary> 次の Step で処理するワープ入力があるか </summary>
        private bool _isWarpRequested;

        /// <summary> 実行中のワープの速度（m/s） </summary>
        private Vector3 _warpVelocity;

        /// <summary> 実行中のワープの残りの所要時間（秒） </summary>
        private float _warpTimeRemaining;

        /// <summary> 次のワープができるまでの残り時間（秒） </summary>
        private float _warpCooldownRemaining;

        /// <param name="playerBoard">PlayerMovementState の登録先</param>
        /// <param name="inputState">移動・ダッシュ・ジャンプ・ワープ入力の取得元</param>
        /// <param name="settingState">ダッシュ入力の受け付け方の取得元</param>
        /// <param name="parameters">移動のパラメータ</param>
        /// <param name="sceneId">State を紐づけるシーンのビルドインデックス</param>
        public PlayerMovementService(PlayerBoard playerBoard, IInputState inputState,
            IOperationSettingState settingState, PlayerParameterData parameters, int sceneId)
        {
            _settingState = settingState;
            _parameters = parameters;
            _wallRunTimeRemaining = parameters.WallRunDuration;

            playerBoard.RegisterSceneState<IPlayerMovementState>(_state, sceneId);

            // PlayerContactState は EngineAdapterLayer が登録するので、登録を待ち受けて拾う
            _contactStateWaiter = playerBoard.SubscribeStateRegister<IPlayerContactState>(
                () =>
                {
                    if (playerBoard.TryGetSceneState<IPlayerContactState>(out var state, out _))
                    {
                        _contactState = state;
                    }
                },
                invokeIfRegistered: true);

            _subscriptions.Add(inputState.RegisterInput<Vector2>(ActionMaps.Player, PlayerActions.Move, OnMove));
            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.Sprint, OnSprint));
            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.Jump, OnJump));
            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.Warp, OnWarp));
        }

        /// <summary> ダッシュ入力の受け付け方に応じて、押下中またはトグルの状態を返す </summary>
        private bool IsSprinting => _settingState.SprintInputMode == SprintInputMode.Hold
            ? _isSprintHeld
            : _isSprintToggled;

        /// <summary> 地面に触れているか </summary>
        private bool IsGrounded => _contactState != null && (_contactState.Contacts & PlayerContact.Ground) != 0;

        /// <summary> 空中で壁に触れているか。地面と壁の両方に触れているときは地面を優先して false </summary>
        private bool IsTouchingWallInAir => _contactState != null && !IsGrounded &&
                                            (_contactState.Contacts & PlayerContact.Wall) != 0;

        /// <summary>
        /// EngineAdapterLayer の FixedUpdate から物理の 1 ステップごとに呼ばれ、記録済みの入力と視線の向き、
        /// 触れている物から移動モードと目標速度を決めて State に書き込む。
        /// ジャンプ入力とワープ入力はこのステップで処理し、行えなければ捨てる。
        /// ワープ中はジャンプ入力も壁走りに入る判定も無視する。
        /// </summary>
        /// <param name="viewDirection">ワールド空間の視線の向き</param>
        /// <param name="deltaTime">このステップの経過時間（秒）</param>
        /// <returns>このステップで Rigidbody に与える打ち出し速度。ジャンプしたステップだけ値を持つ</returns>
        public Vector3? Step(Vector3 viewDirection, float deltaTime)
        {
            UpdateViewForward(viewDirection);

            var worldInput = ToWorldDirection(_moveInput);
            var isJumpRequested = _isJumpRequested;
            _isJumpRequested = false;
            var isWarpRequested = _isWarpRequested;
            _isWarpRequested = false;

            if (_state.Mode == PlayerMoveMode.Warping)
            {
                if (_warpTimeRemaining > 0f)
                {
                    AdvanceWarp(deltaTime);
                    return null;
                }

                _state.SetMode(PlayerMoveMode.Normal);
                _warpCooldownRemaining = _parameters.WarpCooldown;
            }
            else
            {
                _warpCooldownRemaining = Mathf.Max(0f, _warpCooldownRemaining - deltaTime);

                if (isWarpRequested && _warpCooldownRemaining <= 0f)
                {
                    StartWarp(viewDirection, worldInput);
                    AdvanceWarp(deltaTime);
                    return null;
                }
            }

            if (IsGrounded)
            {
                _wallRunTimeRemaining = _parameters.WallRunDuration;
            }

            if (!IsTouchingWallInAir)
            {
                _isWaitingWallRelease = false;
            }

            if (_state.Mode == PlayerMoveMode.WallRunning)
            {
                if (isJumpRequested)
                {
                    _state.SetMode(PlayerMoveMode.Normal);
                    _isWaitingWallRelease = true;
                    _state.SetTargetVelocity(Vector3.zero);
                    return CalculateWallJumpVelocity(worldInput);
                }

                if (ShouldExitWallRun(worldInput, deltaTime))
                {
                    _state.SetMode(PlayerMoveMode.Normal);
                }
            }
            else if (CanEnterWallRun(worldInput))
            {
                _state.SetMode(PlayerMoveMode.WallRunning);
                _wallDetachInputTime = 0f;
            }

            if (_state.Mode == PlayerMoveMode.WallRunning)
            {
                _state.SetTargetVelocity(ProjectOnWall(worldInput) * _parameters.WallRunSpeed);
                return null;
            }

            var speed = IsSprinting ? _parameters.SprintSpeed : _parameters.WalkSpeed;
            _state.SetTargetVelocity(worldInput * speed);

            if (!isJumpRequested || !IsGrounded) return null;

            return Vector3.up * CalculateJumpSpeed();
        }

        /// <summary>
        /// 壁走りに入れるかどうか。空中で壁に触れ、前向きの移動入力と壁の法線のなす角が WallDetachAngle より大きく、
        /// 持ち時間が残り、壁ジャンプ後の待ちが解けているときに入れる。
        /// </summary>
        private bool CanEnterWallRun(Vector3 worldInput)
        {
            return IsTouchingWallInAir && _moveInput.y > 0f && !IsPullingAwayFromWall(worldInput) &&
                   _wallRunTimeRemaining > 0f && !_isWaitingWallRelease;
        }

        /// <summary>
        /// 入力が壁から離れる向き（壁の法線とのなす角が WallDetachAngle 以下）かどうか。入力が 0 のときは false。
        /// </summary>
        private bool IsPullingAwayFromWall(Vector3 worldInput)
        {
            return worldInput.sqrMagnitude > Mathf.Epsilon &&
                   Vector3.Angle(worldInput, _contactState.WallNormal) <= _parameters.WallDetachAngle;
        }

        /// <summary>
        /// 壁走りの持ち時間と、壁から離れようとする入力の継続時間を進め、壁走りを抜けるかどうかを返す。
        /// 壁との接触が切れたとき、持ち時間が尽きたとき、壁から離れる向きの入力が一定時間続いたときに抜ける。
        /// </summary>
        private bool ShouldExitWallRun(Vector3 worldInput, float deltaTime)
        {
            if (!IsTouchingWallInAir) return true;

            _wallRunTimeRemaining -= deltaTime;
            if (_wallRunTimeRemaining <= 0f)
            {
                _wallRunTimeRemaining = 0f;
                return true;
            }

            _wallDetachInputTime = IsPullingAwayFromWall(worldInput) ? _wallDetachInputTime + deltaTime : 0f;
            return _wallDetachInputTime >= _parameters.WallDetachTime;
        }

        /// <summary>
        /// 入力から壁の法線方向の成分を取り除き、壁の面に沿った水平な向きにする。長さは残った成分の長さになる。
        /// </summary>
        private Vector3 ProjectOnWall(Vector3 worldInput)
        {
            return Vector3.ProjectOnPlane(worldInput, _contactState.WallNormal);
        }

        /// <summary>
        /// 壁ジャンプの打ち出し速度を求める。
        /// 水平方向は、入力から壁へ押し込む成分を取り除いた向きと、壁の法線とを WallJumpInputInfluence の割合で混ぜた向き。
        /// 入力が 0 のときは法線の向き。上向きの速度はジャンプと同じ。
        /// </summary>
        private Vector3 CalculateWallJumpVelocity(Vector3 worldInput)
        {
            var wallNormal = _contactState.WallNormal;

            var pushIntoWall = Vector3.Dot(worldInput, wallNormal);
            var input = pushIntoWall < 0f ? worldInput - wallNormal * pushIntoWall : worldInput;

            var horizontalDirection = input.sqrMagnitude > Mathf.Epsilon
                ? Vector3.Lerp(wallNormal, input.normalized, _parameters.WallJumpInputInfluence).normalized
                : wallNormal;

            return horizontalDirection * _parameters.WallJumpHorizontalSpeed + Vector3.up * CalculateJumpSpeed();
        }

        /// <summary>
        /// ワープを始める。移動モードを Warping にし、向きと速度、所要時間を決める。
        /// 向きは、視線の向き ＋ ワールド空間の入力 × WarpInputInfluence を正規化したもの。
        /// 視線の向きがほぼ 0 のときは、水平な視線の向きを使う。
        /// </summary>
        private void StartWarp(Vector3 viewDirection, Vector3 worldInput)
        {
            var view = viewDirection.sqrMagnitude > 1e-6f ? viewDirection.normalized : _viewForward;
            var direction = (view + worldInput * _parameters.WarpInputInfluence).normalized;
            if (direction.sqrMagnitude <= Mathf.Epsilon)
            {
                direction = view;
            }

            _warpVelocity = direction * (_parameters.WarpDistance / _parameters.WarpDuration);
            _warpTimeRemaining = _parameters.WarpDuration;
            _state.SetMode(PlayerMoveMode.Warping);
        }

        /// <summary>
        /// ワープを 1 ステップ分進める。目標速度にワープの速度を書き込み、残りの所要時間を減らす。
        /// 残りの所要時間がステップの経過時間より短いときは、進む距離が WarpDistance に揃うよう速度をその割合だけ落とす。
        /// </summary>
        private void AdvanceWarp(float deltaTime)
        {
            var ratio = deltaTime > 0f ? Mathf.Clamp01(_warpTimeRemaining / deltaTime) : 0f;
            _state.SetTargetVelocity(_warpVelocity * ratio);
            _warpTimeRemaining -= deltaTime;
        }

        /// <summary>
        /// ジャンプの高さから、ジャンプの初速を求める。高さ h まで上がる初速は v = √(2gh)。
        /// </summary>
        private float CalculateJumpSpeed()
        {
            return Mathf.Sqrt(2f * Mathf.Abs(Physics.gravity.y) * _parameters.JumpHeight);
        }

        private void OnMove(InputContext<Vector2> context)
        {
            _moveInput = context.Phase == InputPhase.Canceled
                ? Vector2.zero
                : Vector2.ClampMagnitude(context.Value, 1f);

            if (_moveInput.sqrMagnitude <= Mathf.Epsilon)
            {
                _isSprintToggled = false;
            }
        }

        private void OnSprint(InputContext<float> context)
        {
            switch (context.Phase)
            {
                case InputPhase.Performed:
                    _isSprintHeld = true;
                    _isSprintToggled = !_isSprintToggled;
                    break;
                case InputPhase.Canceled:
                    _isSprintHeld = false;
                    break;
            }
        }

        private void OnJump(InputContext<float> context)
        {
            if (context.Phase == InputPhase.Performed)
            {
                _isJumpRequested = true;
            }
        }

        private void OnWarp(InputContext<float> context)
        {
            if (context.Phase == InputPhase.Performed)
            {
                _isWarpRequested = true;
            }
        }

        /// <summary>
        /// 視線の向きを水平面へ投影して保持する。水平成分があるときだけ更新する。
        /// </summary>
        private void UpdateViewForward(Vector3 viewDirection)
        {
            viewDirection.y = 0f;
            if (viewDirection.sqrMagnitude < 1e-6f) return;

            _viewForward = viewDirection.normalized;
        }

        /// <summary>
        /// 入力（x が右、y が前）を、水平な視線の向きを前方としたワールド方向へ変換する。長さは入力の長さを保つ。
        /// </summary>
        private Vector3 ToWorldDirection(Vector2 input)
        {
            var right = Vector3.Cross(Vector3.up, _viewForward);
            return right * input.x + _viewForward * input.y;
        }

        public void Dispose()
        {
            foreach (var subscription in _subscriptions)
            {
                subscription.Dispose();
            }

            _subscriptions.Clear();
            _contactStateWaiter.Dispose();
        }
    }
}
