using System;
using System.Collections.Generic;
using AutoGenerated;
using Kizami.BlackBoard;
using UnityEngine;
using UsefulToolkit.BlackBoard.Input;

namespace Kizami.Application
{
    /// <summary>
    /// 入力から「移動方向」と「目標速度」を決めて PlayerMovementState に書き込むユースケース。
    /// PlayerMovementState の具象インスタンスはこのクラスだけが保持する（Single Writer）。
    /// 毎フレーム処理は持たず、入力イベントに反応して State を更新するだけ。
    /// 実際の物理反映と加減速の補間は EngineServiceLayer 側（PlayerMovementAbstracter）が行う。
    /// </summary>
    public sealed class PlayerMovementService : IDisposable
    {
        private readonly PlayerMovementState _state = new();
        private readonly float _moveSpeed;
        private readonly List<IDisposable> _subscriptions = new();

        /// <param name="playerBoard">PlayerMovementState の登録先</param>
        /// <param name="inputBoard">移動入力チャンネルの取得元</param>
        /// <param name="sceneId">State を紐づけるシーンのビルドインデックス</param>
        /// <param name="moveSpeed">MovementSpeed の上限値（m/s）</param>
        public PlayerMovementService(PlayerBoard playerBoard, InputBoard inputBoard, int sceneId, float moveSpeed)
        {
            _moveSpeed = moveSpeed;

            playerBoard.RegisterSceneState<IPlayerMovementState>(_state, sceneId);

            var moveChannel = inputBoard.GetChannel<Vector2>(ActionMaps.Player, PlayerActions.Move);
            _subscriptions.Add(moveChannel.Register(OnMove));
        }

        private void OnMove(InputContext<Vector2> context)
        {
            if (context.IsCanceled)
            {
                _state.ChangeMovementDirection(Vector3.zero);
                _state.ChangeMovementSpeed(0f);
                return;
            }

            var raw = context.Value;
            var direction = new Vector3(raw.x, 0f, raw.y);
            var magnitude = Mathf.Clamp01(direction.magnitude);

            _state.ChangeMovementDirection(magnitude > Mathf.Epsilon ? direction.normalized : Vector3.zero);
            _state.ChangeMovementSpeed(magnitude * _moveSpeed);
        }

        public void Dispose()
        {
            foreach (var subscription in _subscriptions)
            {
                subscription.Dispose();
            }

            _subscriptions.Clear();
        }
    }
}
