using System;
using System.Collections.Generic;
using AutoGenerated;
using Kizami.BlackBoard;
using Kizami.External;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Input;

namespace Kizami.Application
{
    /// <summary>
    /// スキル 1〜3 の入力を受けて、その枠に装備しているスキルの分のチャージを消費し、効果の実行役を呼ぶユースケース。
    /// </summary>
    public sealed class SkillService : IDisposable
    {
        /// <summary> 装備枠の数 </summary>
        public const int SLOT_COUNT = 3;

        private readonly SkillData[] _slots = new SkillData[SLOT_COUNT];
        private readonly SkillSlotState _slotState = new(SLOT_COUNT);
        private readonly ChargeService _chargeService;
        private readonly Action<float, float> _onBeam;
        private readonly Action<float> _onExplosion;
        private readonly List<IDisposable> _subscriptions = new();

        /// <param name="blackBoard">SkillSlotState の登録先と、入力の取得元</param>
        /// <param name="equippedSkills">枠ごとに装備するスキル。空きの枠と、SLOT_COUNT を超えた分は無視する</param>
        /// <param name="chargeService">発動に使うチャージの消費先</param>
        /// <param name="onBeam">ビームを出す関数。引数は長さ（m）と半径（m）</param>
        /// <param name="onExplosion">爆発を出す関数。引数は半径（m）</param>
        /// <param name="sceneId">State を紐づけるシーンのビルドインデックス</param>
        public SkillService(IBlackBoard blackBoard, IReadOnlyList<SkillData> equippedSkills,
            ChargeService chargeService, Action<float, float> onBeam, Action<float> onExplosion, int sceneId)
        {
            _chargeService = chargeService;
            _onBeam = onBeam;
            _onExplosion = onExplosion;

            var count = Math.Min(equippedSkills.Count, SLOT_COUNT);
            for (var i = 0; i < count; i++)
            {
                _slots[i] = equippedSkills[i];
                if (_slots[i] != null) _slotState.SetSlot(i, _slots[i].Cost);
            }

            if (!blackBoard.TryGetBoard<PlayerBoard>(out var playerBoard, this) ||
                !blackBoard.TryGetGameState<InputBoard, IInputState>(out var inputState, this)) return;

            playerBoard.RegisterSceneState<ISkillSlotState>(_slotState, sceneId);

            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.Skill1,
                context => OnSkill(context, 0)));
            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.Skill2,
                context => OnSkill(context, 1)));
            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.Skill3,
                context => OnSkill(context, 2)));
        }

        /// <summary>
        /// 枠にスキルがあり、その消費量だけチャージを消費できたら、スキルの効果を出す。
        /// </summary>
        private void OnSkill(InputContext<float> context, int slot)
        {
            if (context.Phase != InputPhase.Performed) return;

            var skill = _slots[slot];
            if (skill == null) return;
            if (!_chargeService.TryConsume(skill.Cost)) return;

            switch (skill.Effect)
            {
                case SkillEffect.Beam:
                    _onBeam?.Invoke(skill.Length, skill.Radius);
                    break;
                case SkillEffect.Explosion:
                    _onExplosion?.Invoke(skill.Radius);
                    break;
            }
        }

        public void Dispose()
        {
            foreach (var subscription in _subscriptions)
            {
                subscription.Dispose();
            }

            _subscriptions.Clear();
        }
    }
}
