using System;
using System.Collections.Generic;
using System.Threading;
using AutoGenerated;
using Cysharp.Threading.Tasks;
using Kizami.BlackBoard;
using Kizami.External;
using UnityEngine;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Input;

namespace Kizami.Application
{
    /// <summary>
    /// スローモードの入力を受けて、チャージを消費して時間の倍率を下げ、続けている間もチャージを消費するユースケース。
    /// 入力でもう一度切り替えるか、チャージが 0 になると終わる。
    /// スローモード中に近接切断を振れる回数を数え、上限に達したらスローモードが終わるまで振らせない。
    /// </summary>
    public sealed class SlowModeService : IDisposable
    {
        private readonly SlowModeState _state = new();
        private readonly PlayerParameterData _parameters;
        private readonly ChargeService _chargeService;
        private readonly ITimeScaleController _timeScaleController;
        private readonly IChargeState _chargeState;
        private readonly List<IDisposable> _subscriptions = new();

        private CancellationTokenSource _drainCancellation;

        /// <param name="blackBoard">SlowModeState の登録先と、入力・チャージ量の取得元</param>
        /// <param name="parameters">倍率と消費量の取得元</param>
        /// <param name="chargeService">発動と継続に使うチャージの消費先</param>
        /// <param name="timeScaleController">時間の倍率を変える操作面</param>
        /// <param name="sceneId">State を紐づけるシーンのビルドインデックス</param>
        public SlowModeService(IBlackBoard blackBoard, PlayerParameterData parameters, ChargeService chargeService,
            ITimeScaleController timeScaleController, int sceneId)
        {
            _parameters = parameters;
            _chargeService = chargeService;
            _timeScaleController = timeScaleController;

            if (!blackBoard.TryGetBoard<PlayerBoard>(out var playerBoard, this) ||
                !blackBoard.TryGetGameState<InputBoard, IInputState>(out var inputState, this) ||
                !blackBoard.TryGetSceneState<PlayerBoard, IChargeState>(out _chargeState, this)) return;

            playerBoard.RegisterSceneState<ISlowModeState>(_state, sceneId);

            _subscriptions.Add(inputState.RegisterInput<float>(ActionMaps.Player, PlayerActions.SlowMode, OnSlowMode));
        }

        /// <summary>
        /// 近接切断を 1 回振ってよいかを判定し、スローモード中なら残りの回数を 1 減らす。
        /// </summary>
        /// <returns>スローモード外か、スローモード中で残りの回数があれば true</returns>
        public bool TryUseCut()
        {
            if (!_state.IsActive) return true;
            if (_state.RemainingCuts <= 0) return false;

            _state.SetRemainingCuts(_state.RemainingCuts - 1);
            return true;
        }

        private void OnSlowMode(InputContext<float> context)
        {
            if (context.Phase != InputPhase.Performed) return;

            if (_state.IsActive)
            {
                End();
            }
            else
            {
                TryBegin();
            }
        }

        /// <summary>
        /// 発動の消費量だけチャージを消費できたら、倍率を下げて継続の消費を始める。
        /// </summary>
        private void TryBegin()
        {
            if (_timeScaleController == null) return;
            if (!_chargeService.TryConsume(_parameters.SlowModeActivationCost)) return;

            _state.SetActive(true);
            _state.SetRemainingCuts(_parameters.SlowModeCutLimit);
            _timeScaleController.SetScale(_parameters.SlowModeTimeScale);

            if (_parameters.SlowModeDrainPerSecond <= 0f) return;

            _drainCancellation = new CancellationTokenSource();
            DrainAsync(_drainCancellation.Token).Forget();
        }

        /// <summary>
        /// 継続の消費を止め、倍率を等速に戻す。
        /// </summary>
        private void End()
        {
            _drainCancellation?.Cancel();
            _drainCancellation?.Dispose();
            _drainCancellation = null;

            _state.SetActive(false);
            _state.SetRemainingCuts(0);
            _timeScaleController?.ResetScale();
        }

        /// <summary>
        /// 毎フレーム、実時間の経過に毎秒の消費量を掛けて溜め、1 以上溜まった分のチャージを消費する。チャージが 0 になったら終える。
        /// 一定間隔で待つ方式だと、待ち終わるフレームの分だけ遅れが積み重なり、消費が少なくなる為、経過時間を溜める。
        /// </summary>
        private async UniTaskVoid DrainAsync(CancellationToken cancellationToken)
        {
            var pending = 0f;

            while (true)
            {
                if (_chargeState.Current <= 0)
                {
                    End();
                    return;
                }

                var isCanceled = await UniTask.Yield(PlayerLoopTiming.Update, cancellationToken)
                    .SuppressCancellationThrow();
                if (isCanceled) return;

                pending += Time.unscaledDeltaTime * _parameters.SlowModeDrainPerSecond;
                if (pending < 1f) continue;

                var amount = (int)pending;
                pending -= amount;
                _chargeService.TryConsume(Math.Min(amount, _chargeState.Current));
            }
        }

        /// <summary>
        /// 入力の購読を解除する。スローモード中なら終えて、倍率を等速に戻す。
        /// </summary>
        public void Dispose()
        {
            foreach (var subscription in _subscriptions)
            {
                subscription.Dispose();
            }

            _subscriptions.Clear();

            if (_state.IsActive) End();
        }
    }
}
