using Cysharp.Threading.Tasks;
using Kizami.Application;
using Kizami.BlackBoard;
using UnityEngine;
using UsefulToolkit.Attributes;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Logger;
using UsefulToolkit.External.Scene;
using UsefulToolkit.Initialization;
using UsefulToolkit.Utility;

namespace Kizami.Initialization
{
    /// <summary>
    /// シーン遷移の操作面を組み立て、起動時にアウトゲームへ遷移する Initializer。常駐シーンへ置く。
    ///
    /// 場面のシーンは 3 ビルドで共通なので、ビルドモードごとに差し替えるのは
    /// 組み合わせる操作シーンだけになる。PC とスマホは同じシーングループを指定してよい。
    /// 遷移の操作面は DI コンテナへ登録し、受け取る側は
    /// IInjectable&lt;IGameSceneController&gt; を実装する。
    /// </summary>
    [InitializeOrder(InitializeOrderConst.Initializer)]
    public sealed class GameSceneInitializer : InitializerBase
    {
        [SerializeField]
        [Tooltip("アウトゲームで読み込むシーングループ。")]
        private BuildModeSelector<SceneGroupDataBase> _outGameGroups = new();

        [SerializeField]
        [Tooltip("インゲームで読み込むシーングループ。")]
        private BuildModeSelector<SceneGroupDataBase> _inGameGroups = new();

        [SerializeField]
        [Tooltip("起動時にアウトゲームへ自動で遷移する。")]
        private bool _transitionOnStart = true;

        private readonly GameSceneController _sceneController = new();

        private void Awake()
        {
            AutoGenerated.UsefulToolkitPersistentCompositor.TryRegisterContent<IGameSceneController>(_sceneController);
        }

        public override void Initialize(IBlackBoard blackBoard)
        {
            if (!TryBuildSceneGroups(out var sceneGroups)) return;

            if (!blackBoard.TryGetStateBoard<AppBoard>(out var appBoard) ||
                !appBoard.TryGetGameState<IBuildModeState>(out var buildModeState))
            {
                UsefulLogger.LogError(
                    "IBuildModeState が未登録の為、操作系に応じたシーングループを選べません。", this);
                return;
            }

            if (!_sceneController.Initialize(blackBoard, sceneGroups, buildModeState)) return;

            base.Initialize(blackBoard);

            if (_transitionOnStart)
            {
                _sceneController.StartGameAsync(destroyCancellationToken).Forget();
            }
        }

        /// <summary>
        /// GameSceneController が期待する並び（アウトゲームの全ビルドモード分 → インゲームの全ビルドモード分）で
        /// シーングループを 1 本の配列へ連結する。
        /// </summary>
        /// <param name="sceneGroups">組み立てたシーングループ</param>
        /// <returns>全ての枠が設定されていて組み立てられたか</returns>
        private bool TryBuildSceneGroups(out SceneGroup[] sceneGroups)
        {
            sceneGroups = null;

            var sources = new SceneGroupDataBase[BuildModeSelector.Count * 2];
            _outGameGroups.ToArray().CopyTo(sources, 0);
            _inGameGroups.ToArray().CopyTo(sources, BuildModeSelector.Count);

            var groups = new SceneGroup[sources.Length];

            for (int i = 0; i < sources.Length; i++)
            {
                if (sources[i] == null || sources[i].GroupData == null)
                {
                    UsefulLogger.LogError(
                        "シーングループに未設定の枠がある為、シーン遷移を初期化できません。", this);
                    return false;
                }

                groups[i] = sources[i].GroupData;
            }

            sceneGroups = groups;
            return true;
        }
    }
}
