using Cysharp.Threading.Tasks;
using Kizami.Application;
using UnityEngine;
using UsefulToolkit.Attributes;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Logger;
using UsefulToolkit.External.Scene;
using UsefulToolkit.Initialization;
using UsefulToolkit.Utility;

namespace Kizami.Initialization
{
    /// <summary>
    /// シーン遷移の操作面を組み立て、起動時にアウトゲームへ遷移する Initializer。常駐シーンへ置く。
    ///
    /// 遷移の操作面は DI コンテナへ登録し、受け取る側は
    /// IInjectable&lt;IGameSceneController&gt; を実装する。
    /// </summary>
    [InitializeOrder(InitializeOrderConst.Initializer)]
    public sealed class GameSceneInitializer : InitializerBase
    {
        [SerializeField]
        [Tooltip("アウトゲームで読み込むシーングループ。")]
        private SceneGroupDataBase _outGameGroup;

        [SerializeField]
        [Tooltip("インゲームで読み込むシーングループ。")]
        private SceneGroupDataBase _inGameGroup;

        [SerializeField]
        [Tooltip("起動時にアウトゲームへ自動で遷移する。")]
        private bool _transitionOnStart = true;

        private readonly GameSceneController _sceneController = new();

        private void Awake()
        {
            AutoGenerated.UsefulToolkitPersistentCompositor.TryRegisterContent<IGameSceneController>(_sceneController);
        }

        public override void Initialize(IBlackBoard blackBoard)
        {
            if (_outGameGroup == null || _outGameGroup.GroupData == null ||
                _inGameGroup == null || _inGameGroup.GroupData == null)
            {
                UsefulLogger.LogError("シーングループが設定されていない為、シーン遷移を初期化できません。", this);
                return;
            }

            if (!_sceneController.Initialize(blackBoard, _outGameGroup.GroupData, _inGameGroup.GroupData)) return;

            base.Initialize(blackBoard);

            if (_transitionOnStart)
            {
                _sceneController.StartGameAsync(destroyCancellationToken).Forget();
            }
        }
    }
}
