// 自動生成ファイルの為、手動での編集は上書きされます。
// 生成元シーン : PlayerMoveTest

using UnityEngine;

namespace AutoGenerated
{
    /// <summary>PlayerMoveTest の合成ルート。</summary>
    public sealed class PlayerMoveTestCompositor : UsefulToolkit.Initialization.GameCompositor<AutoGenerated.PlayerMoveTestCompositor>
    {
        [SerializeField] private Kizami.Initialization.PlayerInitializer _playerInitializer;

        protected override void InjectAll()
        {
            // IInjectableを実装したInitializerはありません。
        }

        protected override void InitializeAll(UsefulToolkit.BlackBoard.BlackBoard.IBlackBoard blackBoard)
        {
            if (_playerInitializer != null) _playerInitializer.Initialize(blackBoard);
        }
    }
}
