using AutoGenerated;
using Kizami.Application;
using Kizami.EngineAdapter;
using Kizami.External;
using UnityEngine;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Logger;
using UsefulToolkit.Initialization;

namespace Kizami.Initialization
{
    /// <summary>
    /// プレイヤーの移動・視点・HP・近接切断・チャージまわり（Service / State / Adapter）を生成して繋ぐ配線役。インゲームのシーンへ置く。
    /// 操作系ごとの視点の回転のさせ方の違いは、シーンへ置く PlayerMovementAdapterBase の派生が吸収する。
    /// </summary>
    public sealed class PlayerInitializer : InitializerBase
    {
        private readonly PlayerHealthService _healthService = new();

        [SerializeField]
        [Tooltip("プレイヤーの移動・HP・近接切断・チャージのパラメータ")]
        private PlayerParameterData _parameters;

        [SerializeField] private PlayerMovementAdapterBase _movementAdapter;
        [SerializeField] private PlayerCameraAdapterBase _cameraAdapter;
        [SerializeField] private MeleeCutPreviewAdapter _meleeCutPreviewAdapter;
        [SerializeField] private MeleeCutAdapter _meleeCutAdapter;
        [SerializeField] private FragmentOrbAdapter _fragmentOrbAdapter;

        private PlayerMovementService _movementService;
        private PlayerLookService _lookService;
        private MeleeCutService _meleeCutService;
        private ChargeService _chargeService;

        public override void Initialize(IBlackBoard blackBoard)
        {
            if (_parameters == null)
            {
                UsefulLogger.LogError("PlayerParameterData が設定されていません。", this);
                base.Initialize(blackBoard);
                return;
            }

            var sceneId = gameObject.scene.buildIndex;
            _movementService = new PlayerMovementService(blackBoard, _parameters, sceneId);
            _lookService = new PlayerLookService(blackBoard, sceneId);
            _chargeService = new ChargeService(blackBoard, _parameters, sceneId);

            if (_fragmentOrbAdapter != null)
            {
                _fragmentOrbAdapter.Initialize(_chargeService.AddFragments);
            }
            else
            {
                UsefulLogger.LogError("FragmentOrbAdapter が設定されていません。", this);
            }

            if (_meleeCutAdapter != null)
            {
                _meleeCutAdapter.Initialize(_fragmentOrbAdapter != null ? _fragmentOrbAdapter.ReceiveCutResults : null);
            }
            else
            {
                UsefulLogger.LogError("MeleeCutAdapter が設定されていません。", this);
            }

            _meleeCutService = new MeleeCutService(blackBoard, _parameters,
                _meleeCutAdapter != null ? _meleeCutAdapter.Swing : null, sceneId);

            // PlayerHealthService は PlayerMovementState を取得する為、PlayerMovementService の生成より後に初期化する
            _healthService.Initialize(blackBoard, _parameters, sceneId);

            // 以降の Adapter は Service が登録した State を取得する為、Service の生成より後に初期化する
            if (_movementAdapter != null)
            {
                _movementAdapter.Initialize(blackBoard, _movementService.Step);
            }
            else
            {
                UsefulLogger.LogError("PlayerMovementAdapterBase が設定されていません。", this);
            }

            // カメラの上下方向反映は操作系によっては使わない（例: VR は HMD の姿勢が担う）為、未設定でもエラーにしない
            if (_cameraAdapter != null)
            {
                _cameraAdapter.Initialize(blackBoard);
            }

            if (_meleeCutPreviewAdapter != null)
            {
                _meleeCutPreviewAdapter.Initialize(blackBoard);
            }
            else
            {
                UsefulLogger.LogError("MeleeCutPreviewAdapter が設定されていません。", this);
            }

            base.Initialize(blackBoard);
        }

        private void Awake()
        {
            InGameCompositor.TryRegisterContent(_healthService);
        }

        private void OnDestroy()
        {
            _movementService?.Dispose();
            _lookService?.Dispose();
            _meleeCutService?.Dispose();
        }
    }
}
