using AutoGenerated;
using Kizami.Application;
using Kizami.BlackBoard;
using Kizami.EngineAdapter;
using Kizami.External;
using UnityEngine;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Input;
using UsefulToolkit.BlackBoard.Logger;
using UsefulToolkit.Initialization;

namespace Kizami.Initialization
{
    /// <summary>
    /// プレイヤーの移動・視点・HP・近接切断・チャージまわり（Service / State / Adapter）を生成して繋ぐ配線役。インゲームのシーンへ置く。
    /// 操作系ごとの視点の回転のさせ方の違いは、シーンへ置く PlayerMovementAdapterBase の派生が吸収する。
    /// </summary>
    public sealed class PlayerInitializer : InitializerBase
    {
        [SerializeField] private PlayerMovementAdapterBase movementAdapter;
        [SerializeField] private PlayerCameraAdapterBase cameraAdapter;
        [SerializeField] private MeleeCutPreviewAdapter meleeCutPreviewAdapter;
        [SerializeField] private MeleeCutAdapter meleeCutAdapter;
        [SerializeField] private FragmentOrbAdapter fragmentOrbAdapter;

        [SerializeField]
        [Tooltip("プレイヤーの移動・HP・近接切断・チャージのパラメータ")]
        private PlayerParameterData _parameters;

        private readonly PlayerHealthService _healthService = new();

        private PlayerMovementService _movementService;
        private PlayerLookService _lookService;
        private MeleeCutService _meleeCutService;
        private ChargeService _chargeService;

        private void Awake()
        {
            InGameCompositor.TryRegisterContent(_healthService);
        }

        public override void Initialize(IBlackBoard blackBoard)
        {
            if (!blackBoard.TryGetStateBoard<PlayerBoard>(out var playerBoard))
            {
                UsefulLogger.LogError(
                    "PlayerBoard が未登録です。常駐シーンの Root Compositor を再生成してください。", this);
                base.Initialize(blackBoard);
                return;
            }

            if (!blackBoard.TryGetStateBoard<InputBoard>(out var inputBoard))
            {
                UsefulLogger.LogError(
                    "InputBoard が未登録です。常駐シーンの Root Compositor を再生成してください。", this);
                base.Initialize(blackBoard);
                return;
            }

            // IInputState は InputInitializer が GameState として登録する。
            // このシーンの Compositor は常駐シーンの初期化後に走るため、通常はここで取得できる。
            if (!inputBoard.TryGetGameState<IInputState>(out var inputState))
            {
                UsefulLogger.LogError(
                    "IInputState が未登録です。常駐シーンから Play しているか、InputInitializer の初期化順を確認してください。", this);
                base.Initialize(blackBoard);
                return;
            }

            if (!blackBoard.TryGetStateBoard<AppBoard>(out var appBoard) ||
                !appBoard.TryGetGameState<IOperationSettingState>(out var settingState))
            {
                UsefulLogger.LogError(
                    "IOperationSettingState が未登録です。常駐シーンの初期化順を確認してください。", this);
                base.Initialize(blackBoard);
                return;
            }

            if (_parameters == null)
            {
                UsefulLogger.LogError("PlayerParameterData が設定されていません。", this);
                base.Initialize(blackBoard);
                return;
            }

            var sceneId = gameObject.scene.buildIndex;
            _movementService = new PlayerMovementService(
                playerBoard, inputState, settingState, _parameters, sceneId);

            _lookService = new PlayerLookService(playerBoard, inputState, settingState, sceneId);

            _chargeService = new ChargeService(playerBoard, _parameters, sceneId);

            if (fragmentOrbAdapter != null)
            {
                fragmentOrbAdapter.Initialize(_chargeService.AddFragments);
            }
            else
            {
                UsefulLogger.LogError("FragmentOrbAdapter が設定されていません。", this);
            }

            if (meleeCutAdapter != null)
            {
                meleeCutAdapter.Initialize(fragmentOrbAdapter != null ? fragmentOrbAdapter.ReceiveCutResults : null);
            }
            else
            {
                UsefulLogger.LogError("MeleeCutAdapter が設定されていません。", this);
            }

            _meleeCutService = new MeleeCutService(playerBoard, inputState, settingState, _parameters,
                meleeCutAdapter != null ? meleeCutAdapter.Swing : null, sceneId);

            // PlayerHealthService は PlayerMovementState を取得する為、PlayerMovementService の生成より後に初期化する
            _healthService.Initialize(playerBoard, _parameters, sceneId);

            if (movementAdapter != null)
            {
                movementAdapter.Initialize(playerBoard, _movementService.Step);
            }
            else
            {
                UsefulLogger.LogError("PlayerMovementAdapterBase が設定されていません。", this);
            }

            // カメラの上下方向反映は操作系によっては使わない（例: VR は HMD の姿勢が担う）為、未設定でもエラーにしない
            if (cameraAdapter != null)
            {
                cameraAdapter.Initialize(playerBoard);
            }

            if (meleeCutPreviewAdapter != null)
            {
                meleeCutPreviewAdapter.Initialize(playerBoard);
            }
            else
            {
                UsefulLogger.LogError("MeleeCutPreviewAdapter が設定されていません。", this);
            }

            base.Initialize(blackBoard);
        }

        private void OnDestroy()
        {
            _movementService?.Dispose();
            _lookService?.Dispose();
            _meleeCutService?.Dispose();
        }
    }
}
