using Kizami.Application;
using Kizami.EngineAdapter;
using UnityEngine;
using UsefulToolkit.Attributes;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Logger;
using UsefulToolkit.Initialization;
using UsefulToolkit.Utility;

namespace Kizami.Initialization
{
    /// <summary>
    /// 時間の倍率（TimeScaleService / TimeScaleState / TimeScaleAdapter）を生成して繋ぐ配線役。
    /// 倍率はシーンを跨いで保たれるので、常駐シーンへ置いて一度だけ生成する。
    /// </summary>
    [InitializeOrder(InitializeOrderConst.InitializerEarly - 10)]
    public sealed class TimeScaleInitializer : InitializerBase
    {
        private readonly TimeScaleService _service = new();

        [SerializeField] private TimeScaleAdapter _adapter;

        public override void Initialize(IBlackBoard blackBoard)
        {
            _service.Initialize(blackBoard);

            // TimeScaleAdapter は TimeScaleState を取得する為、TimeScaleService の初期化より後に初期化する
            if (_adapter != null)
            {
                _adapter.Initialize(blackBoard);
            }
            else
            {
                UsefulLogger.LogError("TimeScaleAdapter が設定されていません。", this);
            }

            base.Initialize(blackBoard);
        }

        private void Awake()
        {
            AutoGenerated.UsefulToolkitPersistentCompositor.TryRegisterContent<ITimeScaleController>(_service);
        }
    }
}
