using Kizami.Application;
using Kizami.BlackBoard;
using Kizami.EngineAdapter;
using UnityEngine;
using UsefulToolkit.Attributes;
using UsefulToolkit.BlackBoard.BlackBoard;
using UsefulToolkit.BlackBoard.Logger;
using UsefulToolkit.Initialization;
using UsefulToolkit.Utility;

namespace Kizami.Initialization
{
    /// <summary>
    /// 時間の倍率（TimeScaleService / TimeScaleState / TimeScaleAdapter）を生成して繋ぐ配線役。
    /// 倍率はシーンを跨いで保たれるので、常駐シーンへ置いて一度だけ生成する。
    /// </summary>
    [InitializeOrder(InitializeOrderConst.InitializerEarly - 10)]
    public sealed class TimeScaleInitializer : InitializerBase
    {
        [SerializeField] private TimeScaleAdapter _adapter;

        private readonly TimeScaleService _service = new();

        private void Awake()
        {
            AutoGenerated.UsefulToolkitPersistentCompositor.TryRegisterContent<ITimeScaleController>(_service);
        }

        public override void Initialize(IBlackBoard blackBoard)
        {
            if (!blackBoard.TryGetStateBoard<AppBoard>(out var appBoard))
            {
                UsefulLogger.LogError("AppBoard が未登録の為、TimeScaleState を登録できません。", this);
                base.Initialize(blackBoard);
                return;
            }

            _service.Initialize(appBoard);

            if (_adapter != null)
            {
                _adapter.Initialize(appBoard);
            }
            else
            {
                UsefulLogger.LogError("TimeScaleAdapter が設定されていません。", this);
            }

            base.Initialize(blackBoard);
        }
    }
}
