// このファイルはUsefulToolkit.Inputによって自動生成されています。直接編集しないでください。
namespace AutoGenerated
{
    public enum PlayerActions
    {
        Move,
        Look,
        Attack,
        Interact,
        Jump,
        Sprint,
        CutRotate,
        Warp,
        SlowMode,
        Throw,
        LoadLauncher,
        FireLauncher,
        Skill1,
        Skill2,
        Skill3,
    }
}
