// このファイルはUsefulToolkit.Inputによって自動生成されています。直接編集しないでください。
namespace AutoGenerated
{
    public enum SmartphoneActions
    {
        Move,
        Look,
        AttackVertical,
        AttackHorizontal,
        AttackUpperRight,
        AttackUpperLeft,
        Previous,
        Next,
        Sprint,
    }
}
