// このファイルはUsefulToolkit.Inputによって自動生成されています。直接編集しないでください。
namespace AutoGenerated
{
    public enum VRControllersActions
    {
        Move,
        Look,
        PushGripLeft,
        PushGripRight,
        PushTriggerLeft,
        PushTriggerRight,
    }
}
