// このファイルはUsefulToolkit.Inputによって自動生成されています。直接編集しないでください。
namespace AutoGenerated
{
    public enum VRTransformActions
    {
        HeadPosition,
        HeadRotation,
        LeftHandPosition,
        LeftHandRotation,
        RightHandPosition,
        RightHandRotation,
    }
}
