// 自動生成ファイルの為、手動での編集は上書きされます。

namespace AutoGenerated
{
    public enum NonBuildScenes
    {
        ShaderTest = -1,
        VoxelModelTest = -2,
        VoxelTest = -3,
        InGame = -4,
        OutGame = -5,
        VRTestScene = -6
    }
}
