// 自動生成ファイルの為、手動での編集は上書きされます。

namespace AutoGenerated
{
    public enum NonBuildScenes
    {
        PlayerMoveTest = -1,
        ShaderTest = -2,
        VoxelModelTest = -3,
        VoxelTest = -4,
        OutGame = -5,
        VRTestScene = -6
    }
}
